application: tweet-scraper
version: 1
runtime: python
api_version: 1

handlers:
- url: /static
  static_dir: static

- url: /listener.*
  script: listener.py

- url: /.*
  script: controller.py

builtins:
- datastore_admin: on
